### ISSUE TITLE
[BUG] seec构建部署出错

### ISSUE THREAD

**Issue by ShaoxunZeng** [se4/Doc#3]
- [x] 我已经查阅所有过去的 issue 并没有发现重复。

**Describe the bug**
就帮我部署了前三次commit 后面push上去的没有自动构建，在部署页面找不到镜像

**Comment by GuardOfDawn** [comment]
请问能不能提供一下你们的小组编号或名称？

> * [x]  我已经查阅所有过去的 issue 并没有发现重复。
> 
> **Describe the bug**
> 就帮我部署了前三次commit 后面push上去的没有自动构建，在部署页面找不到镜像

**Comment by ShaoxunZeng** [comment]
已经正常了 谢谢
